### YamlMime:Role 
title: Инженер AI
metadata: 
  title: Инженер по искусственному интеллекту
  description: Инженеры AI используют Cognitive Services (когнитивные службы), Machine Learning (машинное обучение) и Knowledge Mining (майнинг знаний) для разработки и внедрения решений Microsoft AI. 
uid: role.ai-engineer 
summary: | 
  Инженеры AI используют Cognitive Services (когнитивные службы), Machine Learning (машинное обучение) и Knowledge Mining (майнинг знаний) для разработки и внедрения решений Microsoft AI.
subTitle: Инженеры AI используют Cognitive Services (когнитивные службы), Machine Learning (машинное обучение) и Knowledge Mining (майнинг знаний) для разработки и внедрения решений Microsoft AI.
certificationPaths: 
- title: Инженер Azure AI 
  linkedInKeywords: Инженер Azure AI 
  uid: certification-path.azure-ai-engineer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-ai-engineer
    levels:
    - intermediate
certifications:
- uid: certification.azure-ai-engineer
  requiredExams:
  - uid: exam.ai-102
resources:
- title: Руководство по образовательным курсам и сертификациям Microsoft
  description: Изучите все сертификаты в кратком руководстве по обучению и сертификации.
  href: https://aka.ms/TrainingCertDeck
- title: Буклет по образовательным курсам и сертификациям 
  description: Выберите свой путь к успеху с этим буклетом по образовательным курсам и сертификациям.
  href: https://aka.ms/traincertposter
- title: Поддержка сертификационных
  href: ../help.md
  description: Получить помощь через форум поддержки сертификации Microsoft Модератор форума ответит в течение одного рабочего дня, с понедельника по пятницу.
