### YamlMime:Role 
title: Developer [Разработчик] 
metadata: 
  title: Developer [Разработчик] 
  description: Разработчики проектируют, создают, тестируют и обслуживают решения. Разработчики внедряют приложения и службы, сотрудничая с архитекторами решений и клиентами.
uid: role.developer 
summary: | 
  Разработчики проектируют, создают, тестируют и обслуживают решения. Разработчики внедряют приложения и службы, сотрудничая с архитекторами решений и клиентами. 
subTitle: Developers [Разработчики] проектируют, создают, тестируют и поддерживают облачные решения.
certificationPaths: 
- title: Azure Developer
  linkedInKeywords: Azure Developer
  uid: certification-path.developer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-developer
    levels:
    - intermediate 
- title: Разработчик приложений для финансов и операций Dynamics 365
  linkedInKeywords: Разработчик приложений для финансов и операций Dynamics 365
  uid: certification-path.d365-finance-and-operations-apps-developer-associate
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
- title: Microsoft 365 Developer
  linkedInKeywords: Microsoft 365 Developer
  uid: certification-path.m365-developer-associate
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-developer-associate
    levels:
    - intermediate 
-  title: Power Platform Developer
  linkedInKeywords: Power Platform Developer
  uid: certification-path.power-platform-developer-associate
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-platform-developer-associate
    levels:
    - intermediate
certifications:
- uid: certification.azure-developer
  requiredExams:
  - uid: exam.az-204
- uid: certification.d365-finance-and-operations-apps-developer-associate
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-500
- uid: certification.m365-developer-associate
  requiredExams:
  - uid: exam.ms-600
- uid: certification.power-platform-developer-associate
  requiredExams:
  - uid: exam.pl-400
- uid: certification.azure-iot-developer-specialty
  requiredExams:
  - uid: exam.az-220
resources:
- title: Руководство по образовательным курсам и сертификациям Microsoft
  description: Изучите все сертификаты в кратком руководстве по обучению и сертификации.
  href: https://aka.ms/TrainingCertDeck
- title: Буклет по образовательным курсам и сертификациям
  description: Выберите свой путь к успеху с этим буклетом по образовательным курсам и сертификациям.
  href: https://aka.ms/traincertposter
- title: Поддержка по вопросам сертификации
  href: ../help.md
  description: Получить помощь через форум поддержки сертификации Microsoft. Модератор форума ответит в течение одного рабочего дня, с понедельника по пятницу.
