### YamlMime:Role 
title: Функциональный консультант 
metadata: 
  title: Функциональный консультант  
  description: Функциональные консультанты используют Microsoft Dynamics 365 для прогнозирования и планирования потребностей клиентов.  
uid: role.functional-consultant 
summary: | 
  Функциональные консультанты используют Microsoft Dynamics 365 для прогнозирования и планирования потребностей клиентов.
subTitle: Функциональные консультанты используют Microsoft Dynamics 365 для прогнозирования и планирования потребностей клиентов.
certificationPaths: 
- title: Функциональный консультант Dynamics 365 Customer Service
  linkedInKeywords: Функциональный консультант Dynamics 365 Customer Service
  uid: certification-path.d365-functional-consultant-customer-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
    
- title: Функциональный консультант Dynamics 365 Field Service
  linkedInKeywords: Функциональный консультант Dynamics 365 Field Service
  uid: certification-path.d365-functional-consultant-field-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate

- title: Функциональный консультант Dynamics 365 Finance
  linkedInKeywords: Функциональный консультант Dynamics 365 Finance
  uid: certification-path.d365-functional-consultant-financials 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate


- title: Функциональный консультант Dynamics 365 Manufacturing
  linkedInKeywords: Функциональный консультант Dynamics 365 Manufacturing
  uid: certification-path.d365-functional-consultant-manufacturing
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate

- title: Функциональный консультант Dynamics 365 Marketing
  linkedInKeywords: Функциональный консультант Dynamics 365 Marketing
  uid: certification-path.d365-functional-consultant-marketing 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate

- title: Функциональный консультант Dynamics 365 Sales 
  linkedInKeywords: Функциональный консультант Dynamics 365 Sales 
  uid: certification-path.d365-functional-consultant-sales 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate

- title: Функциональный консультант Dynamics 365 Supply Chain Management
  linkedInKeywords: Функциональный консультант Dynamics 365 Supply Chain Management
  uid: certification-path.d365-functional-consultant-supply-chain-management
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate

certifications:
- uid: certification.d365-functional-consultant-customer-service
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-230  

- uid: certification.d365-functional-consultant-field-service
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-240

- uid: certification.d365-functional-consultant-financials
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-310  


- uid: certification.d365-functional-consultant-manufacturing
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-320  

- uid: certification.d365-functional-consultant-marketing
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-220  

- uid: certification.d365-functional-consultant-sales
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-210  

- uid: certification.d365-functional-consultant-supply-chain-management
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-330  
resources:
- title: Руководство по образовательным курсам и сертификациям Microsoft 
  description: Изучите все сертификаты в кратком руководстве по обучению и сертификации.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Буклет по образовательным курсам и сертификациям 
  description: Выберите свой путь к успеху с этим буклетом по образовательным курсам и сертификациям.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Поддержка сертификационных
  href: ../help.md
  description: Получить помощь через форум поддержки сертификации Microsoft Модератор форума ответит в течение одного рабочего дня, с понедельника по пятницу.
