### YamlMime:FAQ
metadata:
  title: 'FAQ: планирование курсов для Learning Partner на сайте Learn | Microsoft Docs'
  description: 'FAQ: планирование курсов для Learning Partner на сайте Learn'
  documentationcenter: NA 
  author: micsullivan
  ms.topic: article
  ms.tgt_pltfrm: NA
  ms.workload: NA
  ms.date: 09/01/2020
  ms.author: msulliv
  ms.prod: non-product-specific
    
title: 'FAQ: планирование курсов для Learning Partner на сайте Learn'
summary: |

  ## Обучение под руководством инструктора

sections:
  - name: Обучение под руководством инструктора
    questions:
      - question: |
          Что представляет собой служба планирования обучения под руководством инструктора Microsoft Learning Partner?
        answer: |
          Корпорация Microsoft упрощает и оптимизирует процесс обучения, добавляя в [**Microsoft Learn**](/learn) возможности планирования обучения под руководством инструктора в реальном времени. Интеграция расписания курсов в Microsoft Learn позволит учащимся предварительно ознакомиться с учебными курсами под руководством инструктора, предлагаемыми квалифицированными Learning Partner. После выбора курса вы будете перенаправлены непосредственно на сайт Learning Partner для завершения регистрации и оплаты.
          
          В настоящее время эта служба работает в ‘Режиме общедоступного предварительного ознакомления’ и регистрация на курс будет доступна только на английском языке. Дополнительные подходящие Learning Partner будут добавлены в течение следующего года.
          
      - question: |
          Какие курсы доступны в сервисе планирования обучения под руководством инструктора Learning Partner?
        answer: |
          По состоянию на 22 сентября 2020 года следующие курсы доступны с сервисом планирования. По мере добавления дополнительных партнеров по обучению будут дополнительные курсы.
          
          1. Microsoft Azure Fundamentals (2 день)
          2. Microsoft Azure Fundamentals (1 день)
          3. Microsoft Azure Administrator
          4. Developing Solutions for Microsoft Azure
          5. Designing and Implementing an Azure AI Solution
          6. Designing and Implementing a Data Science Solution on Azure
          7. Designing an Azure Data Solution
          8. Implementing an Azure Data Solution
          9. Designing for Identity and Security
          10. Deploying and Configuring Infrastructure
          11. Microsoft Azure Architect Design
          12. Microsoft Azure Security Technologies
          13. Установка Windows 10
          14. Dynamics 365: Power Platform Applications
          15. Office 365 Management
          16. Managing Microsoft 365 Identity and Access
          17. Microsoft 365 Fundamentals
          
      - question: |
          Нужно ли мне создавать профиль для использования Microsoft Learn?
        answer: |
          Нет, создавать профиль не требуется. Вы по-прежнему можете получать доступ к маршрутам онлайн-обучения и использовать их, [просматривать курсы под руководством инструктора](/learn/certifications/courses/browse/) и [найти партнера по обучению Microsoft Learning в стране или регионе](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country) без необходимости создавать профиль.
          
          При планировании курса обучения под руководством инструктора в Microsoft Learn вы будете перенаправлены на сайт выбранного партнера по обучению для завершения регистрации и оплаты. Партнеры по обучению могут потребовать, чтобы вы вошли в свой профиль на их сайте.
          
      - question: |
          Какие функции станут доступны при создании профиля Microsoft Learn и входе в систему?
        answer: |
          - Отслеживать прогресс в обучении
          - Создавать коллекции модулей и делиться ими
          - Сохранять закладки
          - Накапливать баллы и достижения
          - Использовать бесплатную версию Azure
          - Просматривать индивидуальные рекомендации
          
      - question: |
          Я зарегистрировался на курс у партнера по обучению на Microsoft Learn, но не получил подтверждение регистрации. Что мне делать?
        answer: |
          Проверьте нежелательную почту или спам в своем почтовом ящике. Возможно, письмо от партнера по обучению для курса, на который вы зарегистрировались, находится там.
          
          Если письмо с подтверждением по-прежнему не удается найти письмо, обратитесь к партнеру по обучению, у которого вы записались на занятие. Партнер по обучению может помочь устранить любые проблемы с почтой и/или подтвердить регистрацию на курс. Контактную информацию партнера по обучению можно найти по адресу: [найти партнера по обучению Microsoft Learning в стране или регионе](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          Я регистрируюсь на курс и попадаю на сайт партнера по обучению, но в моей корзине ничего нет.
        answer: |
          Пожалуйста, свяжитесь с поставщиком услуг обучения, выбранным вами для курса, чтобы решить эту проблему. Контактную информацию партнера по обучению можно найти по адресу: [найти партнера по обучению Microsoft Learning в стране или регионе](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          Мне нужно отменить или перенести курс.
        answer: |
          Свяжитесь с партнером по обучению напрямую. Контактную информацию партнера по обучению можно найти по адресу: [найти партнера по обучению Microsoft Learning в стране или регионе](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          Цена, указанная на сайте Learn, не совпадает с ценой, указанной при оформлении заказа.
        answer: |
          В качестве цены всегда должны использоваться суммы, указанные на сайте или в корзине партнера по обучению, даже если в Learn указана другая сумма.
          
          Возможно, окончательная цена на сайте или в корзине партнера по обучению будет отличаться, так как в нее может быть уже включен налог, или налог необходимо рассчитать во время оформления заказа. Это может включать налог с продаж и налог на добавленную стоимость (VAT). Окончательная сумма, которую вы заплатите, также может зависеть от местонахождения покупателя или языка курса.
          
          В процессе оформления заказа некоторые партнеры по обучению могут предлагать дополнительные услуги. Цена этих услуг может изменить окончательную цену, которую вы увидите при оформлении заказа.
          
      - question: |
          Когда я увижу эти курсы в моей стране или регионе?
        answer: |
          Это новая услуга, которая была выпущена в виде Общедоступной предварительной версии с небольшим количеством квалифицированных Learning Partner для тестирования функциональности и точной настройки процесса. Первоначально курс будет планироваться на английском языке с добавлением дополнительных Learning Partner в течение следующих 12 месяцев.
          
      - question: |
          Почему другие курсы обучения дороже или дешевле тех, которые я хочу посетить?
        answer: |
          Как на любом рынке, стоимость курса определяется каждым партнером по обучению индивидуально. Партнеры должны предоставить полный курс обучения на официальном курсе Microsoft по цене, указанной в инструменте планирования Microsoft Learn. Партнерам разрешается рекламировать дополнительные продукты и услуги, которые не являются обязательными. Если вы считаете, что рекламируемые цены вводят в заблуждение или неточны, свяжитесь с нами через [Расписание курсов под руководством инструктора Learning Partner на форуме поддержки Learn](https://trainingsupport.microsoft.com/en-us/iltvilt/forum).
          
      - question: |
          Фильтрация по местоположению курса, дате и т. д. не работает должным образом.
        answer: |
          Если фильтрация не работает, обновите страницу в браузере и попробуйте еще раз. Если вы чувствуете, что фильтры по-прежнему не работают, вы можете задать свой вопрос в [Планирование курса под руководством инструктора Learning Partner на форуме поддержки Learn](https://trainingsupport.microsoft.com/en-us/iltvilt/forum). Это лучший ресурс для поиска и обращения за помощью, сообщения о проблеме и получения совета.
          
      - question: |
          Я не могу найти Learning Partner в моем районе.
        answer: |
          Если вы не видите Learning Partner или курс, который ищете, вы можете найти дополнительные дни и часы непосредственно на сайте Learning Partner помимо того, что отображается в Microsoft Learn.  Learning Partner не обязаны публиковать расписания для всех своих занятий. Вы можете найти список всех партнеров Microsoft Learning по адресу [найти партнера по обучению Microsoft Learning в стране или регионе](/learn/Certifications/partners#find-a-microsoft-learning-partner-by-country).
          
          Запуская эту новую услугу, мы ограничиваем количество квалифицированных Learning Partner. В течение следующего года будут добавлены Learning Partner, соответствующие определенным критериям.
          
      - question: |
          Я обратился через канал поддержки Learning Partner и не получил никакого ответа.
        answer: |
          Learning Partner несет ответственность за предоставление поддержки, связанной с планированием на своем сайте. Вы можете попробовать посмотреть другие числа на веб-сайте Learning Partner.
          
          Если вы по-прежнему не можете связаться с Learning Partner, вы можете разместить свой вопрос на странице [Планирование курса под руководством инструктора Learning Partner на форуме поддержки Learn](https://trainingsupport.microsoft.com/en-us/iltvilt/forum). Это лучший ресурс, где можно попросить о помощи, сообщить о проблеме и получить совет.
